seed: 42
batch_size: 8
optimizer: Adam
optimizer_args:
    lr: 0.001
    amsgrad: True
epochs: 400
epoch_length: 2
outputpath: experiments_avconvtasnet
model: AV_ConvTasNet
train_scp: data_list/train.scp
train_dur: data_list/train_dur
cv_scp: data_list/val.scp
cv_dur: data_list/val_dur
eval_scp: data_list/test.scp
eval_dur: data_list/test_dur
loss: SI_SNR
n_saved: 1
num_workers: 6
validate_every: 1
with_amp: False
backend: nccl
nproc_per_node: 2
