seed: 42
batch_size: 8
optimizer: Adam
optimizer_args:
    lr: 0.001
    amsgrad: True
epochs: 400
epoch_length: 2
outputpath: experiments_muse
model: MuSE
train_scp: /mnt/user/linjiuxin/ssd/voxceleb2/meta/train.scp
train_dur: /mnt/user/linjiuxin/ssd/voxceleb2/meta/train_dur
cv_scp: /mnt/user/linjiuxin/ssd/voxceleb2/meta/val.scp
cv_dur: /mnt/user/linjiuxin/ssd/voxceleb2/meta/val_dur
eval_scp: /mnt/user/linjiuxin/ssd/voxceleb2/meta/test.scp
eval_dur: /mnt/user/linjiuxin/ssd/voxceleb2/meta/test_dur
loss: MuSE_loss
n_saved: 1
num_workers: 6
validate_every: 1
with_amp: False
backend: nccl
nproc_per_node: 2
